name: Create GitHub Issue from Webhook Payload

on:
  workflow_dispatch
  # You might want to use a scheduled event like "schedule" or trigger on specific actions like "push" for a production workflow.

jobs:
  create-issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Delivery IDs
      id: extract-delivery-ids
      run: |
        # Extract Delivery IDs from the webhook payload
        API_RESPONSE=$(curl -s -X GET -u ${{ secrets.API_TOKEN }} "https://api.github.com/repos/${{ github.repository }}/hooks/${{ secrets.WEBHOOK_HOOK_ID }}/deliveries")
        DELIVERY_IDS=$(echo "$API_RESPONSE" | jq -r '.[].id')
        echo "Delivery IDs: $DELIVERY_IDS"
        echo "::set-output name=delivery_ids::$DELIVERY_IDS"

    - name: Process Delivery IDs
      id: process-delivery-ids
      run: |
        DELIVERY_IDS="${{ steps.extract-delivery-ids.outputs.delivery_ids }}"
        IFS=$'\n' read -rd '' -a DELIVERY_ID_ARRAY <<< "$DELIVERY_IDS"

        for DELIVERY_ID in "${DELIVERY_ID_ARRAY[@]}"; do
          echo "Processing DELIVERY_ID: $DELIVERY_ID"
          PAYLOAD=$(curl -s -X GET -u ${{ secrets.API_TOKEN }} "https://api.github.com/repos/${{ github.repository }}/hooks/${{ secrets.WEBHOOK_HOOK_ID }}/deliveries/${DELIVERY_ID}")
          
          if [ -z "$PAYLOAD" ]; then
            echo "No payload found for DELIVERY_ID $DELIVERY_ID."
            continue
          fi

          ACTION=$(echo "$PAYLOAD" | jq -r '.action')

          # Check if the action is "created" and proceed to create the issue
          if [ "$ACTION" == "created" ]; then
            SECRET=$(echo "$PAYLOAD" | jq -r '.request.payload.alert.secret_type')
            HTML_URL=$(echo "$PAYLOAD" | jq -r '.request.payload.alert.html_url')
            ASSIGNEE="srkambham"  # Specify the assignee's username here
            echo "Creating issue for DELIVERY_ID $DELIVERY_ID"
            echo "SECRET: $SECRET"
            echo "HTML_URL: $HTML_URL"
            ISSUE_RESPONSE=$(curl -X POST -u ${{ secrets.API_TOKEN }} -d "{\"title\":\"$SECRET\",\"body\":\"$HTML_URL\",\"assignees\":[\"$ASSIGNEE\"]}" "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/issues")
            echo "GitHub Issue Creation Response for DELIVERY_ID $DELIVERY_ID: $ISSUE_RESPONSE"
          else
            echo "Action for DELIVERY_ID $DELIVERY_ID is not 'created'. Skipping."
          fi
        done

    - name: Issue Created
      if: success()
      run: echo "GitHub issues created successfully."
