name: Create GitHub Issue from Webhook Payload

on:
  workflow_dispatch

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Delivery ID from Webhook Payload
        id: extract-delivery-id
        run: |
          API_RESPONSE=$(curl -s -X GET -u ${{ secrets.API_TOKEN }} "https://api.github.com/repos/${{ github.repository }}/hooks/${{ secrets.WEBHOOK_HOOK_ID }}/deliveries")
          DELIVERY_ID=$(echo "$API_RESPONSE" | jq -r '.[0].id')

          if [ -z "$DELIVERY_ID" ]; then
            echo "No deliveries found or error in API response."
            exit 1
          fi

          echo "Delivery ID: $DELIVERY_ID"
          echo "$API_RESPONSE" >> deliveries.json

      - name: Get Admin Collaborators
        id: get-admin-collaborators
        run: |
          COLLABORATORS=$(curl -s -X GET -u ${{ secrets.API_TOKEN }} "https://api.github.com/repos/eidikodev/ghas-bootcamp_lab/collaborators")
          ASSIGNEE=""

          if [ -n "$COLLABORATORS" ]; then
            ASSIGNEE=$(echo "$COLLABORATORS" | jq -r '.[] | select(.role_name == "admin") | .login' | head -n 1)
          fi

          echo "$ASSIGNEE" > assignee.txt
          cat assignee.txt

      - name: Process Webhook Payloads
        id: process-payloads
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"
          DELIVERIES=$(cat deliveries.json)
          ASSIGNEE=$(cat assignee.txt)

          echo "Looping Deliveries"
          echo "======================================================================"

          for DELIVERY in $(echo "${DELIVERIES}" | jq -r '.[] | @base64'); do
            _jq() {
              echo "${DELIVERY}" | base64 --decode | jq -r "${1}"
            }
            DELIVERY_ID=$(_jq '.id')

            if [ -z "$DELIVERY_ID" ]; then
              echo "No Delivery ID found. Exiting. Skipping further process for this delivery"
              continue
            fi

            PAYLOAD=$(curl -s -X GET -u ${{ secrets.API_TOKEN }} "https://api.github.com/repos/${{ github.repository }}/hooks/${{ secrets.WEBHOOK_HOOK_ID }}/deliveries/${DELIVERY_ID}")

            if [ -z "$PAYLOAD" ]; then
              echo "No payload found or error in API response. Skipping further process for delivery $DELIVERY_ID"
              continue
            fi

            echo "Webhook Payload"
            ACTION=$(echo "$PAYLOAD" | jq -r '.action')

            if [ "$ACTION" != "reopened" ]; then
              echo "Action is not 'reopened'. Skipping further process for delivery ID: $DELIVERY_ID"
              continue
            fi

            # Add the timestamp check here to process only within the last 24 hours
            CREATED_AT=$(echo "$PAYLOAD" | jq -r '.created_at')
            OLDEST_ALLOWED_TIMESTAMP=$(date -d '24 hours ago' --rfc-3339=seconds)

            if [ "$CREATED_AT" \< "$OLDEST_ALLOWED_TIMESTAMP" ]; then
              echo "Delivery ID $DELIVERY_ID is older than 24 hours. Skipping further process."
              continue
            fi

            echo "Action is 'reopened' and within the last 24 hours. Continuing further Issue creation process for delivery ID: $DELIVERY_ID"
            SECRET=$(echo "$PAYLOAD" | jq -r '.request.payload.alert.secret_type')
            HTML_URL=$(echo "$PAYLOAD" | jq -r '.request.payload.alert.html_url')
            ASSIGNEE=$(cat assignee.txt)

            echo "Creating GitHub Issue"
            COLLABORATORS=$(curl -s -X GET -u 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 "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/collaborators")
		        echo "Collaborators are - "
		        echo "$COLLABORATORS"
		
		        if [ -n "$COLLABORATORS" ]; then
		          ASSIGNEE=$(echo "$COLLABORATORS" | jq -r '.[] | select(.role_name == "admin") | .login' | head -n 1)
		        fi
		        echo "Admin for $REPO_OWNER/$REPO_NAME is -> $ASSIGNEE"
            ISSUE_RESPONSE=$(curl -s -X POST -u ${{ secrets.API_TOKEN }} -d "{\"title\":\"$SECRET\",\"body\":\"$HTML_URL\",\"assignees\":[\"$ASSIGNEE\"]}" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues")

            if [ -z "$ISSUE_RESPONSE" ]; then
              echo "Error creating GitHub issue for delivery ID: $DELIVERY_ID"
            else
              echo "GitHub Issue Creation Response:"
              echo "$ISSUE_RESPONSE"
            fi

            echo "======================================================================"
          done
          echo "======================================================================"

      - name: Issue Created
        if: success()
        run: echo "GitHub issues created for deliveries, of action created, successfully."
