name: Create GitHub Issues from Webhook Payload

on:
  
  push
   
jobs:
  create-issues:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Get Webhook Deliveries
      id: get-webhook-deliveries
      run: |
        # Get all webhook deliveries
        API_RESPONSE=$(curl -s -X GET -u ${{ secrets.API_TOKEN }} "https://api.github.com/repos/${{ github.repository }}/hooks/${{ secrets.WEBHOOK_HOOK_ID }}/deliveries")
        echo "::set-output name=deliveries::$API_RESPONSE"

    - name: Get Repository Information
      id: get-repo-info
      run: |
          REPO_INFO=$(curl -s -X GET -u ${{ secrets.API_TOKEN }} "https://api.github.com/repos/eidikodev/ghas-bootcamp_lab")
          echo "::set-output name=repo-info::$REPO_INFO"
    
    - name: Create Issues
      run: |
        deliveries="${{ steps.get-webhook-deliveries.outputs.deliveries }}"

         # Extract the owner's username from the repository information
          OWNER_USERNAME=$(curl -s -X GET -u ${{ secrets.API_TOKEN }} "https://api.github.com/repos/eidikodev/ghas-bootcamp_lab" | jq -r '.owner.login')
        
        for delivery in $(echo "$deliveries" | jq -r '.[].id'); do
          # Get the webhook payload using the Delivery ID
          PAYLOAD=$(curl -s -X GET -u ${{ secrets.API_TOKEN }} "https://api.github.com/repos/${{ github.repository }}/hooks/${{ secrets.WEBHOOK_HOOK_ID }}/deliveries/$delivery")
          
          # Extract the "action" field from the payload
          ACTION=$(echo "$PAYLOAD" | jq -r '.action')
          
          # Get the timestamp of the delivery
          DELIVERY_TIMESTAMP=$(echo "$PAYLOAD" | jq -r '.created_at')
          
          # Calculate the time difference in seconds
          CURRENT_TIMESTAMP=$(date +%s)
          DELIVERY_TIMESTAMP=$(date -d "$DELIVERY_TIMESTAMP" +%s)
          TIME_DIFF=$((CURRENT_TIMESTAMP - DELIVERY_TIMESTAMP))
          
          # Check if the action is "created" and the delivery is within the last 24 hours
          if [ "$ACTION" == "closed_by_user" ] && [ "$TIME_DIFF" -le 86400 ]; then
            URL=$(echo "$PAYLOAD" | jq -r '.request.payload.alert.url')
            HTML_URL=$(echo "$PAYLOAD" | jq -r '.request.payload.alert.html_url')
                        
            # Create an issue with owner as the assignee
            echo "Creating issue for Delivery ID: $delivery"
            ISSUE_RESPONSE=$(curl -X POST -u ${{ secrets.API_TOKEN }} -d "{\"title\":\"$URL\",\"body\":\"$HTML_URL\",\"assignees\":[\"$ASSIGNEE\"]}" "https://api.github.com/repos/${{ github.repository }}/issues")
            
            # Check if the issue creation was successful
            if [[ $ISSUE_RESPONSE == *"created_at"* ]]; then
              echo "GitHub issue created successfully."
            else
              echo "Failed to create GitHub issue."
            fi
          fi
        done
